In [19]:
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import numpy.random as npr
import cv2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline
plt.style.use('bmh')

In [20]:
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow import keras

In [21]:
# Loading Data. replace 'data_train.npy' with 'data_test.npy' and 'labels_train.npy' with 'labels_test.npy'
data_test = np.load('data_train.npy')
labels_test = np.load('labels_train.npy')

labels_names =['Stadium','Building','Traffic Sign','Forest','Flowers',
              'Street','Classroom','Bridge','Statue','Lake']

print(data_test.shape, labels_test.shape)
print(labels_test.shape[0])

(270000, 3124) (3124,)
3124


In [22]:
#loading the model
from keras.models import load_model

y_final_new = labels_test - 1 #to have 0-9 instead of 1-10
number_of_images = labels_test.shape[0]
data_test_resized = np.resize(data_test.transpose(),(number_of_images,300,300,3))

#load
model_new = tf.keras.models.load_model('final_model.h5')

predictions = model_new.predict(data_test_resized)
scores_cnn = tf.nn.softmax(predictions)
scores_cnn_np = np.array(scores_cnn)

In [23]:
#prediciting the classifications
final_scores = scores_cnn_np
print(final_scores)
num_pred = final_scores.shape[0]
final_predictions = np.zeros(num_pred)
#final_scores.shape
for i in range(num_pred):
    index = np.where(final_scores[i,:] == np.amax(final_scores[i,:]))
    final_predictions[i] = index[0] + 1
    
#final_predictions

conf_matrix_boost = confusion_matrix(labels_test, final_predictions)
class_report_boost = classification_report(labels_test, final_predictions)
print(conf_matrix_boost)
print(class_report_boost)

[[9.9079543e-01 9.1863545e-03 5.1192855e-14 ... 1.7908429e-05
  3.6165286e-11 6.2105220e-13]
 [6.6515387e-12 8.3858591e-09 9.5687491e-10 ... 1.9841862e-06
  1.2398922e-10 2.7879628e-06]
 [3.1756457e-12 2.6104717e-12 1.0230800e-10 ... 1.1725881e-06
  1.8123186e-09 5.4435304e-06]
 ...
 [4.8206741e-15 6.8168629e-14 4.4090747e-08 ... 2.5778425e-07
  8.9761741e-08 1.9176966e-11]
 [4.0633331e-05 9.9991417e-01 2.8218333e-06 ... 1.8134955e-05
  2.1393196e-05 5.7280893e-08]
 [7.7930008e-06 6.1542792e-08 9.9760121e-01 ... 2.6216949e-04
  2.1064575e-03 6.0389903e-07]]
[[302   2   2   0   1   1   0   3   1   0]
 [  0 307   0   1   0   1   2   7   6   1]
 [  0   2 298   0   0   1   0   1   5   1]
 [  0   1   0 304   0   0   0   2   0   0]
 [  0   1   1   3 304   0   0   0   0   0]
 [  0   0   2   0   0 304   0   5   1   2]
 [  2   0   0   0   0   2 313   0   0   0]
 [  2   2   2   3   0   1   0 298   2   1]
 [  0   2   0   0   0   1   0   2 305   0]
 [  1   0   1   0   0   2   0   9   0 298]]
     